# Generated by Django 5.1.5 on 2026-09-22 00:22
#
# No toca la base (las tres operaciones son no-op en SQL): solo deja el
# estado de las migraciones igual al modelo. Django lo pedia desde que la
# 0002 se genero sin estas operaciones; sin esto, `makemigrations --check`
# falla y el siguiente `makemigrations` de cualquiera las arrastraba a su
# migracion.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_nombre_consentimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organizacion_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="rol",
            field=models.CharField(
                blank=True,
                choices=[("titular", "Titular"), ("integrante", "Integrante")],
                max_length=20,
                null=True,
            ),
        ),
    ]