# Generated by Django 5.1.5 on 2026-09-22 00:22
#
# No toca la base (las tres operaciones son no-op en SQL): solo deja el
# estado de las migraciones igual al modelo. Django lo pedia desde que la
# 0002 se genero sin estas operaciones; sin esto, `makemigrations --check`
# falla y el siguiente `makemigrations` de cualquiera las arrastraba a su
# migracion.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_nombre_consentimiento'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
