# Generated by Django 5.1.5 on 2026-09-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_managers_user_nombre_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
