# Generated by Django 5.1.5 on 2026-09-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consentimiento_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
