# Generated by Django 5.1.5 on 2026-09-25 22:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_estado_consistente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'organizacion',
                'ordering': ['-creado_en'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('titular', 'Titular'), ('integrante', 'Integrante')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='app.organizacion'),
        ),
    ]
