# Generated by Django 5.1.5 on 2026-09-15 13:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la suscripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('CLP', 'Peso chileno')], default='CLP', max_length=3, verbose_name='Moneda')),
                ('ciclo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], max_length=20, verbose_name='Ciclo de cobro')),
                ('fecha_cobro', models.DateField(verbose_name='Fecha de cobro')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=20, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'subscription',
                'ordering': ['-fecha_cobro'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', Decimal('0'))), name='subscription_monto_positivo')],
            },
        ),
    ]
