# Generated by Django 5.1.5 on 2026-09-21 05:18

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizacion_id', models.UUIDField(db_index=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la suscripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('CLP', 'Peso chileno'), ('USD', 'Dólar estadounidense')], default='CLP', max_length=3, verbose_name='Moneda')),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=20, verbose_name='Frecuencia de cobro')),
                ('fecha_proximo_cobro', models.DateField(verbose_name='Fecha del próximo cobro')),
                ('categoria', models.CharField(choices=[('streaming', 'Streaming'), ('musica', 'Música'), ('productividad', 'Productividad'), ('nube', 'Nube'), ('juegos', 'Juegos'), ('educacion', 'Educación'), ('salud', 'Salud'), ('noticias', 'Noticias'), ('ia', 'Inteligencia Artificial'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('prueba', 'Prueba'), ('activo', 'Activo'), ('por_confirmar', 'Por confirmar'), ('cancelado', 'Cancelado'), ('fantasma', 'Fantasma')], default='activo', max_length=20, verbose_name='Estado')),
                ('fin_prueba', models.DateField(blank=True, null=True, verbose_name='Fin de período de prueba')),
                ('horas_uso_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Horas de uso en el mes')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'subscription',
                'ordering': ['-fecha_proximo_cobro'],
                'abstract': False,
                'indexes': [models.Index(fields=['organizacion_id', '-creado_en'], name='subscriptio_organiz_b2f6c4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', Decimal('0'))), name='subscription_monto_positivo')],
            },
        ),
    ]
