# Generated by Django 5.1.5 on 2026-09-25 22:39

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del proveedor')),
                ('categoria', models.CharField(choices=[('streaming', 'Streaming'), ('musica', 'Música'), ('productividad', 'Productividad'), ('nube', 'Nube'), ('juegos', 'Juegos'), ('educacion', 'Educación'), ('salud', 'Salud'), ('noticias', 'Noticias'), ('ia', 'Inteligencia Artificial'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='app.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizacion_id', models.UUIDField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto cobrado')),
                ('moneda', models.CharField(choices=[('CLP', 'Peso chileno'), ('USD', 'Dólar estadounidense')], default='CLP', max_length=3, verbose_name='Moneda')),
                ('fecha', models.DateField(verbose_name='Fecha del cobro')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='app.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'db_table': 'cobro',
                'ordering': ['-fecha'],
                'abstract': False,
                'indexes': [models.Index(fields=['organizacion_id', '-fecha'], name='cobro_organiz_5afcf0_idx'), models.Index(fields=['suscripcion', '-fecha'], name='cobro_suscrip_cbe619_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', Decimal('0'))), name='cobro_monto_positivo')],
            },
        ),
    ]
