# Generated by Django 5.1.5 on 2026-09-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_proveedor_y_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actividad'),
        ),
    ]
