# Generated by Django 5.1.5 on 2026-09-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subscription_ultima_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={
                'ordering': ['-fecha_proximo_cobro', 'id'],
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
